Repository iron-mental/americano, pull requests merged in 2020-12, with the labels that each got.

#38 공지사항 - 상세, 수정
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/Entity/Notice.swift
  Terminal-iOS/Entity/Terminal.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticePresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatViewProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/Component/ChatTableViewCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/TempChatView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticePresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailLocalDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeWireFrame.swift
Labels: review completed

#43 핫픽스
  Content/Base.lproj/MainInterface.storyboard
  Content/Info.plist
  Content/NotificationViewController.swift
  Service/Info.plist
  Service/NotificationService.swift
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/Entity/Authorization.swift
  Terminal-iOS/Entity/HotKeyword.swift
  Terminal-iOS/Entity/Notice2.swift
  Terminal-iOS/Entity/StudyDetailPost.swift
  Terminal-iOS/Login/IntroRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/DataManager/StudyDetailRemoteManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Network/TerminalAPI.swift
  Terminal-iOS/Network/TerminalLogger.swift
  Terminal-iOS/Network/TerminalNetwork.swift
  Terminal-iOS/Network/TerminalNetworkManager.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/SceneDelegate.swift
  Terminal-iOS/Set/ProfileModify/ProfileModifyRemoteManager.swift
  Terminal-iOS/Set/Set/Component/DefaultCell.swift
  Terminal-iOS/Set/Set/Component/ProfileCell.swift
  Terminal-iOS/Set/Set/SetView.swift
  Terminal-iOS/Study/SearchStudy/Component/HotKeywordCell.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyView.swift
  Terminal-iOS/Study/StudyCategory/CategoryCell.swift
  Terminal-iOS/Study/StudyList/StudyCell.swift
  TestViewController.swift
Labels: HotFix

#44 Coredata UserInfo 적용
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/Assets.xcassets/playstore.imageset/Contents 2.json
  Terminal-iOS/Assets.xcassets/playstore.imageset/playstore 2.png
  Terminal-iOS/CoreDataEntity/LocalUserInfo.swift
  Terminal-iOS/CoreDataModel.xcdatamodeld/CoreDataModel.xcdatamodel/contents
  Terminal-iOS/CoreDataModel/CoreUserInfo+CoreDataClass.swift
  Terminal-iOS/CoreDataModel/CoreUserInfo+CoreDataProperties.swift
  Terminal-iOS/Entity/CoreDataManager.swift
  Terminal-iOS/Entity/Study.swift
  Terminal-iOS/Entity/StudyDetail.swift
  Terminal-iOS/Entity/Terminal.swift
  Terminal-iOS/Login/IntroInteractor.swift
  Terminal-iOS/Login/IntroPresenter.swift
  Terminal-iOS/Login/IntroRemoteDataManager.swift
  Terminal-iOS/Login/IntroView.swift
  Terminal-iOS/MyStudy/Main/Component/MyStudyMainTableViewCell.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainLocalDataManager.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainRemoteDataManager.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticePresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailRemoteDataManager.swift
  Terminal-iOS/SceneDelegate.swift
  Terminal-iOS/Set/ProfileModify/Component/ProfileSNSView 2.swift
  Terminal-iOS/Set/ProfileModify/Component/ProjectCell 2.swift
  Terminal-iOS/Set/ProfileModify/Component/ProjectSNSView 2.swift
  Terminal-iOS/Set/ProfileModify/Component/ProjectTableView 2.swift
  Terminal-iOS/Set/ProfileModify/ProfileModifyInteractor 2.swift
  Terminal-iOS/Set/ProfileModify/ProfileModifyPresenter 2.swift
  Terminal-iOS/Set/ProfileModify/ProfileModifyProtocols 2.swift
  Terminal-iOS/Set/ProfileModify/ProfileModifyRemoteManager 2.swift
  Terminal-iOS/Set/ProfileModify/ProfileModifyWireFrame 2.swift
  Terminal-iOS/Set/Set/Component/UserManageCell 2.swift
  Terminal-iOS/Set/Set/SetInteractor.swift
  Terminal-iOS/Set/Set/SetProtocols.swift
  Terminal-iOS/Set/Set/SetRemoteManager 2.swift
  Terminal-iOS/Set/Set/SetRemoteManager.swift
  Terminal-iOS/Set/Set/SetView.swift
  Terminal-iOS/Set/Set/SetWireFrame.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyView.swift
  Terminal-iOS/Study/StudyList/DataManager/StudyListLocalDataManager.swift
  Terminal-iOS/Study/StudyList/StudyListInteractor.swift
  Terminal-iOS/Study/StudyList/StudyListProtocols.swift
  Terminal-iOS/Study/StudyList/StudyListView.swift
  Terminal-iOS/TerminalCoreData.xcdatamodeld/TerminalCoreData.xcdatamodel/contents
  Terminal-iOS/TerminalModel.xcdatamodeld/TerminalModel.xcdatamodel/contents
  Terminal-iOS/Utils/Contents 2.swift
  Terminal-iOS/Utils/Contents.swift
  TestViewController 2.swift
Labels: review needed

#45 Feature/apply
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/BaseComponent/ApplyListCell.swift
  Terminal-iOS/Entity/ApplyStudy.swift
  Terminal-iOS/Entity/ApplyUser.swift
  Terminal-iOS/Entity/CategoryState.swift
  Terminal-iOS/Entity/Study.swift
  Terminal-iOS/Entity/Terminal.swift
  Terminal-iOS/Login/IntroView.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainPresenter.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainProtocols.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainView.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainWireFrame.swift
  Terminal-iOS/MyStudy/Main/TempMyStudyList.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/DataManager/StudyDetailRemoteManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Network/TerminalLogger.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailView.swift
  Terminal-iOS/Set/ProfileModify/ProfileModifyInteractor.swift
  Terminal-iOS/Set/ProfileModify/ProfileModifyRemoteManager.swift
  Terminal-iOS/Set/ProfileModify/ProfileModifyView.swift
  Terminal-iOS/Set/Set/SetView.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyRemoteManager.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyView.swift
  Terminal-iOS/Study/StudyCategory/DataManager/StudyCategoryLocalDataManager.swift
  Terminal-iOS/Study/StudyList/StudyCell.swift
  Terminal-iOS/Study/StudyList/StudyListInteractor.swift
  Terminal-iOS/Study/StudyList/StudyListPresenter.swift
  Terminal-iOS/TestViewController.swift
  Terminal-iOS/Utils/Contents.swift
  TestViewController.swift
Labels: review completed

#46 Feature/set
  Terminal-iOS/Set/Set/Component/ProfileCell.swift
  Terminal-iOS/Set/Set/SetView.swift
Labels: review completed

#47 CreateStudy 관련 뷰 디테일 잡기
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/Entity/CoreDataManager.swift
  Terminal-iOS/Entity/KeyboardManager.swift
  Terminal-iOS/Entity/LoadingRainbowCat.swift
  Terminal-iOS/Entity/Terminal.swift
  Terminal-iOS/Extensions-Utillities/UIScrollView+Ext.swift
  Terminal-iOS/Study/CreateStudy/Component/LocationUIVIew.swift
  Terminal-iOS/Study/CreateStudy/Component/LocationUIView.swift
  Terminal-iOS/Study/CreateStudy/Component/SNSInputItem.swift
  Terminal-iOS/Study/CreateStudy/Component/SNSInputUIView.swift
  Terminal-iOS/Study/CreateStudy/Component/TimeUIView.swift
  Terminal-iOS/Study/CreateStudy/Component/TitleWithTextView.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyInteractor.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyPresenter.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyProtocols.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyView.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SearchLoaction/SearchLocationView.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SelectLocation/Component/BottomView.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SelectLocation/SelectLocationViewView.swift
  Terminal-iOS/Study/SelectCategory/SelectCategoryView.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryView.swift
  Terminal-iOS/ViewController.swift
Labels: review needed
