Repository iron-mental/americano, pull requests merged in 2021-03, with the labels that each got.

#123 스터디 신청자 상세조회 API 변경에 따른 대응
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/BaseComponent/BaseProfileView.swift
  Terminal-iOS/Entity/ApplyUserInfo.swift
  Terminal-iOS/Entity/Project.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailWireFrame.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Set/MyProfile/Component/ApplyMessageView.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailPresenter.swift
Labels: review needed

#124 프로필 컨텐츠 유무에 따른 상태처리
  Terminal-iOS/BaseComponent/BaseProfileView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailView.swift
  Terminal-iOS/Set/Career/CareerModifyView.swift
  Terminal-iOS/Set/MyProfile/Component/CareerView.swift
  Terminal-iOS/Set/MyProfile/Component/LocationView.swift
  Terminal-iOS/Set/MyProfile/Component/ProfileSNSView.swift
  Terminal-iOS/Set/MyProfile/Component/ProjectListView.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailView.swift
Labels: review needed

#125 디테일 작업
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/BaseComponent/ApplyListCell.swift
  Terminal-iOS/BaseComponent/BaseProfileView.swift
  Terminal-iOS/Entity/LoadingRainbowCat.swift
  Terminal-iOS/Extensions-Utillities/DispatchTimeInterval+Ext.swift
  Terminal-iOS/Extensions-Utillities/UIImageView+Ext.swift
  Terminal-iOS/Extensions-Utillities/UISegmentControl+Ext 2.swift
  Terminal-iOS/Extensions-Utillities/UIViewController+Ext.swift
  Terminal-iOS/FindPassword/FindPasswordResultView.swift
  Terminal-iOS/FindPassword/FindPasswordView.swift
  Terminal-iOS/LaunchView/LaunchInteractor.swift
  Terminal-iOS/LaunchView/LaunchView.swift
  Terminal-iOS/LaunchView/LaunchWireFrame.swift
  Terminal-iOS/Login/HomeView.swift
  Terminal-iOS/Login/IntroView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/NotificationView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailView.swift
  Terminal-iOS/Set/Profile/ProfileModifyInteractor.swift
  Terminal-iOS/Set/Profile/ProfileModifyView.swift
  Terminal-iOS/Set/Set/Component/NotiCell.swift
  Terminal-iOS/Set/Set/Component/ProfileCell.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyView.swift
Labels: review needed

#126 커스텀 폰트 추가에 따른 변경사항 적용
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/BaseComponent/ApplyListCell.swift
  Terminal-iOS/BaseComponent/BaseEditableStudyDetailView.swift
  Terminal-iOS/Entity/FontWeight.swift
  Terminal-iOS/Extensions-Utillities/UIFont+Ext.swift
  Terminal-iOS/Extensions-Utillities/UILabel+Ext.swift
  Terminal-iOS/Extensions-Utillities/UITextField+Ext.swift
  Terminal-iOS/Extensions-Utillities/UITextView+Ext.swift
  Terminal-iOS/Extensions-Utillities/UIViewController+Ext.swift
  Terminal-iOS/FindPassword/FindPasswordResultView.swift
  Terminal-iOS/Info.plist
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyModify/MyApplyStudyModifyView.swift
  Terminal-iOS/Set/Project/ProjectModifyView.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SelectLocation/SelectLocationView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyView.swift
  Terminal-iOS/ViewController.swift
Labels: review needed

#128 신고기능 관련 기능 추가
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/Entity/TerminalAlertMessage.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/DataManager/StudyDetailRemoteManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/StaticComponent/AlertReportContentView.swift
Labels: review needed

#129 applystudy - 신청메세지작성칸 UITextField -> UITextView 변경
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/StaticComponent/StudyApplyMessageView.swift
Labels: review needed

#130 QA 반영 및 잔작업
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/BaseComponent/ApplyListCell.swift
  Terminal-iOS/BaseComponent/BaseEditableStudyDetailView.swift
  Terminal-iOS/BaseComponent/BaseProfileRemoteDataManager.swift
  Terminal-iOS/Entity/EmailValidteResult.swift
  Terminal-iOS/Extensions-Utillities/UIImageView+Ext.swift
  Terminal-iOS/Login/IntroInteractor.swift
  Terminal-iOS/Login/IntroPresenter.swift
  Terminal-iOS/Login/IntroProtocols.swift
  Terminal-iOS/Login/IntroRemoteDataManager.swift
  Terminal-iOS/Login/IntroView.swift
  Terminal-iOS/MyStudy/Main/Component/MyStudyMainTableViewCell.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainInteractor.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainPresenter.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/DelegateHost/DelegateHostView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyInfo/MyApplyStudyInfoView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/NotificationRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Set/Career/CareerModifyInteractor.swift
  Terminal-iOS/Set/Career/CareerModifyPresenter.swift
  Terminal-iOS/Set/Email/EmailModifyInteractor.swift
  Terminal-iOS/Set/Email/EmailModifyPresenter.swift
  Terminal-iOS/Set/Location/LocationModifyInteractor.swift
  Terminal-iOS/Set/Location/LocationModifyPresenter.swift
  Terminal-iOS/Set/Location/LocationModifyRemoteDataManager.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailInteractor.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailPresenter.swift
  Terminal-iOS/Set/Profile/ProfileModifyInteractor.swift
  Terminal-iOS/Set/Profile/ProfileModifyPresenter.swift
  Terminal-iOS/Set/Profile/ProfileModifyRemoteManager.swift
  Terminal-iOS/Set/Project/ProjectModifyInteractor.swift
  Terminal-iOS/Set/Project/ProjectModifyPresenter.swift
  Terminal-iOS/Set/SNS/SNSModifyInteractor.swift
  Terminal-iOS/Set/SNS/SNSModifyPresenter.swift
  Terminal-iOS/Study/CreateStudy/Component/MainImageView.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyInteractor.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyPresenter.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyProtocols.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyRemoteManager.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyView.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SearchLoaction/Component/SearchLocationTableViewCell.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SearchLoaction/SearchLocationInteractor.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SearchLoaction/SearchLocationPresenter.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SearchLoaction/SearchLocationView.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SearchLoaction/SearchLocationWireFrame.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SelectLocation/SelectLocationInteractor.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SelectLocation/SelectLocationPresenter.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyInteractor.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyRemoteDataManager.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyView.swift
  Terminal-iOS/Study/StudyCategory/CategoryCell.swift
  Terminal-iOS/Study/StudyCategory/DataManager/StudyCategoryRemoteManager.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryInteractor.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryPresenter.swift
  Terminal-iOS/Study/StudyList/StudyCell.swift
Labels: review needed

#131 프로필 자기소개 뷰 수정
  Podfile.lock
  Terminal-iOS/Set/Email/EmailModifyView.swift
  Terminal-iOS/Set/Profile/ProfileModifyView.swift
  Terminal-iOS/Set/Project/ProjectModifyView.swift
  Terminal-iOS/Set/SNS/SNSModifyView.swift
Labels: review needed

#133 Feat/alertdetail
  Terminal-iOS/Entity/TerminalAlertMessage.swift
  Terminal-iOS/Entity/VersionResult.swift
  Terminal-iOS/LaunchView/LaunchInteractor.swift
  Terminal-iOS/LaunchView/LaunchPresenter.swift
  Terminal-iOS/LaunchView/LaunchProtocols.swift
  Terminal-iOS/LaunchView/LaunchRemoteDataManager.swift
  Terminal-iOS/LaunchView/LaunchView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/DelegateHost/Component/DelegateHostTableViewCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/MemberCollectionViewCell.swift
  Terminal-iOS/StaticComponent/AlertReportContentView.swift
  Terminal-iOS/StaticComponent/StudyApplyMessageView.swift
Labels: review needed

#134 스터디 생성 수정 유효성 검증 로직 변경
  Terminal-iOS/BaseComponent/BaseEditableStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyView.swift
  Terminal-iOS/StaticComponent/StudyCheck.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyView.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyWireFrame.swift
Labels: review needed

#135 Feat/addnotice count
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/Assets.xcassets/SNSICON/github.imageset/Contents.json
  Terminal-iOS/Assets.xcassets/SNSICON/github.imageset/Image.png
  Terminal-iOS/Assets.xcassets/SNSICON/github.imageset/github.png
  Terminal-iOS/Assets.xcassets/blog.imageset/Contents.json
  Terminal-iOS/Assets.xcassets/blog.imageset/Image.png
  Terminal-iOS/Assets.xcassets/homeImage.imageset/Contents.json
  Terminal-iOS/Assets.xcassets/homeImage.imageset/boyStudyingWithBook113065238@2x.png
  Terminal-iOS/Assets.xcassets/member.imageset/Contents.json
  Terminal-iOS/Assets.xcassets/member.imageset/Image-1.png
  Terminal-iOS/Assets.xcassets/member.imageset/Image-2.png
  Terminal-iOS/Assets.xcassets/member.imageset/Image.png
  Terminal-iOS/Assets.xcassets/more.imageset/Contents.json
  Terminal-iOS/Assets.xcassets/more.imageset/Image 2.png
  Terminal-iOS/Assets.xcassets/more.imageset/Image-1.png
  Terminal-iOS/Assets.xcassets/more.imageset/Image-2 2.png
  Terminal-iOS/Assets.xcassets/playstore.imageset/Contents.json
  Terminal-iOS/Extensions-Utillities/UITapGestureRecognizer.swift
  Terminal-iOS/Login/HomeView.swift
  Terminal-iOS/Login/IntroPresenter.swift
  Terminal-iOS/Login/IntroProtocols.swift
  Terminal-iOS/Login/IntroView.swift
  Terminal-iOS/Login/IntroWireFrame.swift
  Terminal-iOS/Login/ViewConponent/TermsOfServiceView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeView.swift
  Terminal-iOS/Set/Set/SetPresenter.swift
  Terminal-iOS/Set/Set/SetView.swift
Labels: review needed

#136 아이패드 구동 이슈 해결
  Terminal-iOS/BaseComponent/ApplyListCell.swift
  Terminal-iOS/BaseComponent/BaseEditableStudyDetailView.swift
  Terminal-iOS/Entity/TerminalAlertMessage.swift
  Terminal-iOS/Extensions-Utillities/UILabel+Ext.swift
  Terminal-iOS/Extensions-Utillities/UITapGestureRecognizer.swift
  Terminal-iOS/Extensions-Utillities/UITextField+Ext.swift
  Terminal-iOS/Extensions-Utillities/UITextView+Ext.swift
  Terminal-iOS/Extensions-Utillities/UIViewController+Ext.swift
  Terminal-iOS/Login/IntroPresenter.swift
  Terminal-iOS/Login/IntroProtocols.swift
  Terminal-iOS/Login/IntroView.swift
  Terminal-iOS/Login/IntroWireFrame.swift
  Terminal-iOS/Login/ViewConponent/TermsOfServiceView.swift
  Terminal-iOS/MyStudy/Main/Component/MyStudyMainTableViewCell.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyInfo/MyApplyStudyInfoView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Set/Career/CareerModifyView.swift
  Terminal-iOS/Set/Location/LocationModifyView.swift
  Terminal-iOS/Set/Profile/ProfileModifyView.swift
  Terminal-iOS/Set/Project/ProjectModifyView.swift
  Terminal-iOS/Set/Set/SetPresenter.swift
  Terminal-iOS/Set/Set/SetProtocols.swift
  Terminal-iOS/Set/Set/SetView.swift
  Terminal-iOS/Set/Set/SetWireFrame.swift
  Terminal-iOS/Study/CreateStudy/Component/MainImageView.swift
  Terminal-iOS/Study/SelectCategory/SelectCategoryView.swift
Labels: review needed

#138 프로필 수정 유효성 검증 추가
  Podfile.lock
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/BaseComponent/BaseEditableStudyDetailView.swift
  Terminal-iOS/BaseComponent/BaseSNSModifyView.swift
  Terminal-iOS/Entity/Project.swift
  Terminal-iOS/Extensions-Utillities/UIView+Ext.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Set/Career/CareerModifyInteractor.swift
  Terminal-iOS/Set/Career/CareerModifyPresenter.swift
  Terminal-iOS/Set/Career/CareerModifyProtocols.swift
  Terminal-iOS/Set/Career/CareerModifyView.swift
  Terminal-iOS/Set/Email/EmailModifyView.swift
  Terminal-iOS/Set/Profile/ProfileModifyInteractor.swift
  Terminal-iOS/Set/Profile/ProfileModifyPresenter.swift
  Terminal-iOS/Set/Profile/ProfileModifyProtocols.swift
  Terminal-iOS/Set/Profile/ProfileModifyView.swift
  Terminal-iOS/Set/Project/ProjectCell.swift
  Terminal-iOS/Set/Project/ProjectModifyInteractor.swift
  Terminal-iOS/Set/Project/ProjectModifyPresenter.swift
  Terminal-iOS/Set/Project/ProjectModifyProtocols.swift
  Terminal-iOS/Set/Project/ProjectModifyView.swift
  Terminal-iOS/StaticComponent/StudyCheck.swift
  Terminal-iOS/Study/CreateStudy/Component/SNSInputUITextField.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyView.swift
Labels: review needed

#139 Fix/memoryleak
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/1024.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/120-1.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/120.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/152.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/167.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/180.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/20.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/29.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/40-1.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/40-2.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/40.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/58-1.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/58.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/60.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/76.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/80-1.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/80.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/87.png
  Terminal-iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  Terminal-iOS/Login/IntroView.swift
  Terminal-iOS/Set/Set/SetWireFrame.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SelectLocation/SelectLocationView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyView.swift
  Terminal-iOS/Study/SelectCategory/SelectCategoryPresenter.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryView.swift
  Terminal-iOS/Study/StudyList/DataManager/StudyListLocalDataManager.swift
  Terminal-iOS/Study/StudyList/StudyListInteractor.swift
  Terminal-iOS/Study/StudyList/StudyListProtocols.swift
Labels: review needed

#140 프로젝트 라이센스 고지
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/Entity/LibraryLicense.swift
  Terminal-iOS/Set/Licenses/LicenseCell.swift
  Terminal-iOS/Set/Licenses/LicenseDetailView.swift
  Terminal-iOS/Set/Licenses/LicensesView.swift
  Terminal-iOS/Set/Set/SetView.swift
Labels: review needed

#143 아이패드화면깨짐수정, 파이어베이스 연동, 등등
  Podfile
  Podfile.lock
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS.xcodeproj/xcshareddata/xcschemes/Terminal-iOS.xcscheme
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/Assets.xcassets/testImage/marker.imageset/Contents.json
  Terminal-iOS/Assets.xcassets/testImage/marker.imageset/Image.png
  Terminal-iOS/Assets.xcassets/testImage/marker.imageset/testmarker.png
  Terminal-iOS/BaseComponent/TerminalAlertUIView.swift
  Terminal-iOS/EmptyViews/ApplyUserListEmptyView.swift
  Terminal-iOS/EmptyViews/DelegateHostListEmptyView.swift
  Terminal-iOS/EmptyViews/MyApplyListEmptyView.swift
  Terminal-iOS/EmptyViews/SearchLocationEmptyView.swift
  Terminal-iOS/EmptyViews/StudyListEmptyView.swift
  Terminal-iOS/Entity/TerminalAlertMessage.swift
  Terminal-iOS/GoogleService-Info.plist
  Terminal-iOS/MyStudy/Main/MyStudyMainView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/StaticComponent/AlertMessageView.swift
  Terminal-iOS/StaticComponent/EmailAlertMessageView.swift
  Terminal-iOS/Study/StudyList/StudyCell.swift
Labels: review needed

#144 프로필 디폴트 이미지 설정
  Podfile.lock
  Terminal-iOS/Entity/Profile.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailView.swift
  Terminal-iOS/Set/Profile/ProfileModifyView.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyRemoteManager.swift
Labels: review needed

#146 fix : 로그인, 회원가입 후 메모리릭 수정
  Terminal-iOS/Login/IntroView.swift
Labels: HotFix

#151 이미지 API 변경으로 인한 작업
  Terminal-iOS/BaseComponent/BaseEditableStudyDetailView.swift
  Terminal-iOS/BaseComponent/BaseProfileView.swift
  Terminal-iOS/Entity/Profile.swift
  Terminal-iOS/Entity/StudyDetailPost.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailView.swift
  Terminal-iOS/Set/Profile/ProfileModifyInteractor.swift
  Terminal-iOS/Set/Profile/ProfileModifyPresenter.swift
  Terminal-iOS/Set/Profile/ProfileModifyProtocols.swift
  Terminal-iOS/Set/Profile/ProfileModifyRemoteManager.swift
  Terminal-iOS/Set/Profile/ProfileModifyView.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyView.swift
Labels: review needed

#154 fix : typo 실수로 인한 에러 수정
  Terminal-iOS/Set/Project/ProjectCell.swift
Labels: HotFix

#157 Refactor/indexerror
  Terminal-iOS/Set/Set/SetView.swift
  Terminal-iOS/Study/StudyList/StudyListView.swift
Labels: review needed

#161 Fix/study modify
  Terminal-iOS/FindPassword/FindPasswordInteractor.swift
  Terminal-iOS/FindPassword/FindPasswordPresenter.swift
  Terminal-iOS/FindPassword/FindPasswordProtocols.swift
  Terminal-iOS/FindPassword/FindPasswordRemoteDataManager.swift
  Terminal-iOS/FindPassword/FindPasswordView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/MemeberView.swift
Labels: HotFix

#167 채팅
  .Podfile.swp
  Podfile
  Podfile.lock
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS.xcodeproj/xcshareddata/xcschemes/Terminal-iOS.xcscheme
  Terminal-iOS.xcworkspace/contents.xcworkspacedata
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/BaseComponent/BaseEditableStudyDetailView.swift
  Terminal-iOS/CoreDataModel/CoreChatInfo+CoreDataClass.swift
  Terminal-iOS/CoreDataModel/CoreChatInfo+CoreDataProperties.swift
  Terminal-iOS/Entity/Chat.swift
  Terminal-iOS/Entity/ChatParticipate.swift
  Terminal-iOS/Entity/CoreDataManager.swift
  Terminal-iOS/Entity/LoadingRainbowCat.swift
  Terminal-iOS/Entity/RemoteChatInfo.swift
  Terminal-iOS/Extensions-Utillities/UITableView+Ext.swift
  Terminal-iOS/Extensions-Utillities/UITextField+Ext.swift
  Terminal-iOS/Extensions-Utillities/UIViewController+Ext.swift
  Terminal-iOS/Info.plist
  Terminal-iOS/LaunchView/LaunchRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatViewProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/Component/ChatTableViewCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/Component/ChatTableViewOutputCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/TempChatView.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Set/Profile/ProfileModifyInteractor.swift
  Terminal-iOS/Set/Profile/ProfileModifyProtocols.swift
  Terminal-iOS/Set/Profile/ProfileModifyRemoteManager.swift
  Terminal-iOS/Set/UserWithdrawal/UserWithdrawalView.swift
  Terminal-iOS/TerminalCoreData.xcdatamodeld/TerminalCoreData.xcdatamodel/contents
  Terminal-iOS/Utils/Contents.swift
Labels: review completed

#168 Chat/push flow
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/Entity/CoreDataManager.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatViewProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/Component/ChatTableViewOutputCell.swift
Labels: review needed

#169 채팅뷰 요청 사항 수정 및 정리
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatLocalDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatViewProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/Component/ChatTableViewCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/Component/ChatTableViewOutputCell.swift
Labels: review needed

#175 version-up 1.0.4 -> 1.2.0
  Terminal-iOS/Info.plist
Labels: HotFix

#182 스터디 상세 PaddingLabel 버그 수정
  Terminal-iOS/BaseComponent/BaseEditableStudyDetailView.swift
  Terminal-iOS/BaseComponent/PaddingUILabel.swift
  Terminal-iOS/Entity/CoreDataManager.swift
  Terminal-iOS/Entity/LoadingRainbowCat.swift
  Terminal-iOS/Entity/Study.swift
  Terminal-iOS/Entity/TerminalAlertMessage.swift
  Terminal-iOS/Extensions-Utillities/UILabel+Ext.swift
  Terminal-iOS/Extensions-Utillities/UILabel-Ext.swift
  Terminal-iOS/Extensions-Utillities/UITextView+Ext.swift
  Terminal-iOS/LaunchView/LaunchInteractor.swift
  Terminal-iOS/LaunchView/LaunchProtocols.swift
  Terminal-iOS/Login/IntroInteractor.swift
  Terminal-iOS/Login/IntroProtocols.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainProtocols.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Chat/ChatViewProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/DelegateHost/DelegateHostProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyInfo/MyApplyStudyInfoProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/Component/NotificationCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/NotificationProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ParticipantProfile/ParticipantProfileProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/MemberCollectionView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/MemberCollectionViewCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/MemeberView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/StudyDetailSNSView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/TitleWithContentView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Set/Location/LocationModifyView.swift
  Terminal-iOS/Set/Project/ProjectModifyView.swift
  Terminal-iOS/Set/Set/SetInteractor.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyProtocols.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SearchLoaction/SearchLocationProtocols.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SelectLocation/SelectLocationProtocol.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyInteractor.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyProtocols.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultProtocols.swift
  Terminal-iOS/Study/SelectCategory/SelectCategoryProtocols.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryProtocols.swift
  Terminal-iOS/Study/StudyList/StudyCell.swift
  Terminal-iOS/Study/StudyMain/StudyMainInteractor.swift
Labels: review needed
