Repository iron-mental/americano, pull requests merged in 2021-02, with the labels that each got.

#81 NoticeList 로직 변경 + AddNotice 후 처리
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/Entity/EditNoticeResult.swift
  Terminal-iOS/Extensions-Utillities/UIViewController+Ext.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeLocalDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticePresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeWireFrame.swift
Labels: review needed

#83 Fix/study search
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/DelegateHost/DelegateHostPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/DelegateHost/DelegateHostRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyRemoteDataManager.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyInteractor.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyLocalDataManager.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyPresenter.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyProtocols.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyRemoteDataManager.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultInteractor.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultLocalDataManager.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultPresenter.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultProtocols.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultRemoteDataManager.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultWireFrame.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyWireFrame.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryView.swift
  Terminal-iOS/Study/StudyList/DataManager/StudyListRemoteDataManager.swift
Labels: review needed

#85 Feature/study list
  Terminal-iOS/Set/Set/SetView.swift
  Terminal-iOS/Study/StudyList/DataManager/StudyListRemoteDataManager.swift
  Terminal-iOS/Study/StudyList/StudyCell.swift
  Terminal-iOS/Study/StudyList/StudyListInteractor.swift
  Terminal-iOS/Study/StudyList/StudyListPresenter.swift
Labels: review completed

#107 Feat/participateprofile
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/BaseComponent/BaseProfileRemoteDataManager.swift
  Terminal-iOS/Login/IntroRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/Component/NotificationCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/NotificationInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/NotificationPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/NotificationProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/NotificationRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/NotificationView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/NotificationWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ParticapateProfile/ParticipantProfileInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ParticapateProfile/ParticipantProfilePresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ParticapateProfile/ParticipantProfileProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ParticapateProfile/ParticipantProfileRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ParticapateProfile/ParticipantProfileView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ParticapateProfile/ParticipantProfileWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailWireFrame.swift
  Terminal-iOS/Network/BaseInterceptor.swift
Labels: review needed

#108 로그아웃 작업
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Set/Set/SetInteractor.swift
  Terminal-iOS/Set/Set/SetPresenter.swift
  Terminal-iOS/Set/Set/SetProtocols.swift
  Terminal-iOS/Set/Set/SetRemoteManager.swift
  Terminal-iOS/Set/Set/SetView.swift
  Terminal-iOS/Set/Set/SetWireFrame.swift
Labels: review needed

#109 Feat/set noti toggle
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/Entity/LoadingRainbowCat.swift
  Terminal-iOS/Entity/TerminalAlertMessage.swift
  Terminal-iOS/LaunchView/LaunchPresenter.swift
  Terminal-iOS/LaunchView/LaunchRemoteDataManager.swift
  Terminal-iOS/LaunchView/LaunchWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ParticapateProfile/ParticipantProfileView.swift
  Terminal-iOS/Set/Set/Component/NotiCell.swift
  Terminal-iOS/Set/Set/SetPresenter.swift
  Terminal-iOS/Set/Set/SetProtocols.swift
  Terminal-iOS/Set/Set/SetRemoteManager.swift
  Terminal-iOS/Set/Set/SetView.swift
  Terminal-iOS/Set/Set/SetWireFrame.swift
  Terminal-iOS/StaticComponent/AlertMessageView.swift
  Terminal-iOS/StaticComponent/EmailAlertMessageView.swift
  Terminal-iOS/StaticComponent/StudyApplyMessageView.swift
Labels: review completed, review needed

#110 스터디 수정, 생성 유효성 검증 및 기타 작업
  .swiftlint.yml
  Podfile.lock
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/BaseComponent/BaseEditableStudyDetailView.swift
  Terminal-iOS/Entity/StudyDetailPost.swift
  Terminal-iOS/Entity/StudyNilCheck.swift
  Terminal-iOS/Extensions-Utillities/UILabel+Ext.swift
  Terminal-iOS/Extensions-Utillities/UITextField+Ext.swift
  Terminal-iOS/Extensions-Utillities/UITextView+Ext.swift
  Terminal-iOS/Extensions-Utillities/UIViewController+Ext.swift
  Terminal-iOS/Info.plist
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/DelegateHost/DelegateHostView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeViewComponent/NoticeDetailView.swift
  Terminal-iOS/Set/MyProfile/Component/ProfileView.swift
  Terminal-iOS/Set/Project/ProjectModifyInteractor.swift
  Terminal-iOS/Set/Set/SetRemoteManager.swift
  Terminal-iOS/StaticComponent/StudyCheck.swift
  Terminal-iOS/Study/CreateStudy/Component/SNSInputItem.swift
  Terminal-iOS/Study/CreateStudy/Component/TitleWithTextView.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyInteractor.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyPresenter.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyProtocols.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyRemoteManager.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyView.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyWireFrame.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SearchLoaction/SearchLocationWireFrame.swift
  Terminal-iOS/Study/SelectCategory/SelectCategoryView.swift
  Terminal-iOS/Study/SelectCategory/SelectCategoryWireFrame.swift
Labels: review completed

#111 스터디 수정 지역 관련 이슈
  Terminal-iOS/Entity/StudyDetail.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailLocalDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailRemoteDataMananger.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SearchLoaction/SearchLocationPresenter.swift
Labels: HotFix

#116 비밀번호 찾기 기능 구현
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/BaseComponent/ResizableButton.swift
  Terminal-iOS/FindPassword/FindPasswordInteractor.swift
  Terminal-iOS/FindPassword/FindPasswordPresenter.swift
  Terminal-iOS/FindPassword/FindPasswordProtocols.swift
  Terminal-iOS/FindPassword/FindPasswordRemoteDataManager.swift
  Terminal-iOS/FindPassword/FindPasswordResultView.swift
  Terminal-iOS/FindPassword/FindPasswordView.swift
  Terminal-iOS/FindPassword/FindPasswordWireFrame.swift
  Terminal-iOS/Login/HomeView.swift
Labels: review needed

#117 유저의 이메일 나타내는 부분 추가
  Terminal-iOS/FindPassword/FindPasswordResultView.swift
  Terminal-iOS/FindPassword/FindPasswordView.swift
Labels: HotFix

#118 Feature/profile
  Terminal-iOS/BaseComponent/BaseProfileView.swift
  Terminal-iOS/Login/IntroView.swift
  Terminal-iOS/Set/MyProfile/Component/ProfileSNSView.swift
  Terminal-iOS/Set/MyProfile/Component/ProjectListView.swift
  Terminal-iOS/Set/MyProfile/Component/ProjectView.swift
  Terminal-iOS/Set/Project/ProjectModifyView.swift
  Terminal-iOS/Study/StudyList/StudyCell.swift
Labels: HotFix

#120 회원가입 초기 Profile 상세 sns 에러
  Terminal-iOS/BaseComponent/BaseProfileView.swift
Labels: HotFix

#119 QA 티켓들 픽스 및 잔버그 픽스
  Podfile.lock
  Terminal-iOS.xcodeproj/xcshareddata/xcschemes/Terminal-iOS.xcscheme
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/BaseComponent/ApplyListCell.swift
  Terminal-iOS/BaseComponent/BaseProfileView.swift
  Terminal-iOS/Extensions-Utillities/String+Ext.swift
  Terminal-iOS/LaunchView/LaunchInteractor.swift
  Terminal-iOS/Login/IntroRemoteDataManager.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/NotificationInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notification/NotificationRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/StudyDetailSNSView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailWireFrame.swift
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Set/MyProfile/Component/ProjectSNSView.swift
  Terminal-iOS/Set/MyProfile/Component/ProjectView.swift
  Terminal-iOS/Set/Set/Component/ProfileCell.swift
  Terminal-iOS/Set/UserWithdrawal/UserWithdrawalInteractor.swift
  Terminal-iOS/Set/UserWithdrawal/UserWithdrawalPresenter.swift
  Terminal-iOS/Set/UserWithdrawal/UserWithdrawalProtocols.swift
  Terminal-iOS/Set/UserWithdrawal/UserWithdrawalView.swift
  Terminal-iOS/Set/UserWithdrawal/UserWithdrawalWireFrame.swift
  Terminal-iOS/Study/CreateStudy/Component/TitleWithTextView.swift
  Terminal-iOS/Study/StudyList/StudyCell.swift
Labels: review completed

#121 프로필 SNS 상태값, 인터렉션 수정
  Podfile.lock
  Terminal-iOS.xcodeproj/xcshareddata/xcschemes/Terminal-iOS.xcscheme
  Terminal-iOS/BaseComponent/BaseProfileView.swift
  Terminal-iOS/Set/MyProfile/Component/ProfileSNSView.swift
  Terminal-iOS/Set/MyProfile/Component/ProjectSNSView.swift
Labels: review completed
