Repository iron-mental/americano, pull requests merged in 2021-01, with the labels that each got.

#49 스터디 검색 뷰
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/Login/IntroView.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainRemoteDataManager.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/SceneDelegate.swift
  Terminal-iOS/Study/CreateStudyViewController.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyInteractor.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyLocalDataManager.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyPresenter.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyProtocols.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyRemoteDataManager.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultInteractor.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultLocalDataManager.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultPresenter.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultProtocols.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultRemoteDataManager.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultWireFrame.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyWireFrame.swift
  Terminal-iOS/Study/SelectCategory/SelectCategoryWireFrame.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryPresenter.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryProtocols.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryView.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryWireFrame.swift
  Terminal-iOS/Study/StudyList/StudyCell.swift
  Terminal-iOS/Study/StudyList/StudyListInteractor.swift
  Terminal-iOS/Study/StudyList/StudyListView.swift
  Terminal-iOS/Study/StudyList/StudyListWireFrame.swift
Labels: review needed

#50 권한분기, alert 커스텀뷰, 스터디나가기, 스터디 삭제
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/Extensions-Utillities/UIColor+Ext.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainRemoteDataManager.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailRemoteDataMananger.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AlertView/TerminalAlertUIView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/TitleWithContentView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailWireFrame.swift
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyRemoteManager.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultWireFrame.swift
  Terminal-iOS/Study/StudyList/StudyListWireFrame.swift
Labels: review needed

#51 - 푸쉬 이벤트 처리
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/AppDelegate.swift
  Terminal-iOS/Entity/BaseResponse.swift
  Terminal-iOS/Info.plist
  Terminal-iOS/Login/IntroRemoteDataManager.swift
  Terminal-iOS/MyStudy/Main/MyStudyMainView.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailView.swift
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Set/ProfileModify/Component/ProjectCell.swift
  Terminal-iOS/Set/ProfileModify/ProfileModifyView.swift
  Terminal-iOS/ViewController.swift
Labels: review needed

#53 스터디 신청
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/Entity/ApplyUserResult.swift
  Terminal-iOS/Entity/CoreDataManager.swift
  Terminal-iOS/Entity/KeyboardManager.swift
  Terminal-iOS/Entity/LoadingRainbowCat.swift
  Terminal-iOS/Entity/StudyDetailPost.swift
  Terminal-iOS/Entity/Terminal.swift
  Terminal-iOS/Entity/TerminalAlertMessage.swift
  Terminal-iOS/Extensions-Utillities/UIColor+Ext.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailRemoteDataMananger.swift
  Terminal-iOS/MyStudy/StudyDetail/MyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AlertView/TerminalAlertUIView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/Notice/NoticeView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailWireFrame.swift
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Set/Component/ProjectSNSModifyView 2.swift
  Terminal-iOS/Set/Location/LocationModifyWireFrame 2.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailView.swift
  Terminal-iOS/Set/Profile/ProfileModifyRemoteManager 2.swift
  Terminal-iOS/Set/Project/ProjectModifyView 2.swift
  Terminal-iOS/Set/SNS/SNSModifyView 2.swift
  Terminal-iOS/StaticViewComponent/StudyApplyMessageView.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultPresenter.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultProtocols.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultWireFrame.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyView.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryView.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryWireFrame.swift
  Terminal-iOS/Study/StudyList/StudyCell.swift
  Terminal-iOS/Study/StudyList/StudyListPresenter.swift
  Terminal-iOS/Study/StudyList/StudyListProtocols.swift
  Terminal-iOS/Study/StudyList/StudyListView.swift
  Terminal-iOS/Study/StudyList/StudyListWireFrame.swift
  Terminal-iOS/Utils/Contents.swift
  Terminal-iOS/nyancat_big1610346923.json
Labels: review completed

#54 프로필 수정 작업
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/Base.lproj/Main.storyboard
  Terminal-iOS/Entity/Address.swift
  Terminal-iOS/Entity/AddressState.swift
  Terminal-iOS/Extensions-Utillities/Array+Ext.swift
  Terminal-iOS/Extensions-Utillities/UIViewController+Ext.swift
  Terminal-iOS/Info.plist
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Set/Career/CareerModifyView.swift
  Terminal-iOS/Set/Location/LocationCell.swift
  Terminal-iOS/Set/Location/LocationModifyInteractor.swift
  Terminal-iOS/Set/Location/LocationModifyPresenter.swift
  Terminal-iOS/Set/Location/LocationModifyProtocols.swift
  Terminal-iOS/Set/Location/LocationModifyRemoteDataManager.swift
  Terminal-iOS/Set/Location/LocationModifyView.swift
  Terminal-iOS/Set/Location/LocationModifyWireFrame.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailPresenter.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailProtocols.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailView.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailWireFrame.swift
  Terminal-iOS/Set/Profile/ProfileModifyView.swift
  Terminal-iOS/Set/Project/ProjectModifyView.swift
  Terminal-iOS/Set/SNS/SNSModifyProtocols.swift
  Terminal-iOS/Set/SNS/SNSModifyView.swift
  Terminal-iOS/Set/SNS/SNSModifyWireFrame.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyView.swift
  Terminal-iOS/Study/StudyCategory/CategoryCell.swift
  Terminal-iOS/Study/StudyList/DataManager/StudyListRemoteDataManager.swift
  Terminal-iOS/Utils/Contents.swift
Labels: review completed

#56 Feature/study apply accept
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/BaseComponent/BaseProfileRemoteDataManager.swift
  Terminal-iOS/BaseComponent/BaseProfileView.swift
  Terminal-iOS/BaseProtocol/BaseProfileRemoteDataManagerInputProtocol.swift
  Terminal-iOS/Entity/TerminalAlertMessage.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AlertView/TerminalAlertUIView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyList/MyApplyListWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUser/ApplyUserWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailWireFrame.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Set/MyProfile/DataManager/ProfileDetailRemoteManager.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailInteractor.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailPresenter.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailProtocols.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailView.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailWireFrame.swift
  Terminal-iOS/StaticViewComponent/AlertMessageView.swift
  Terminal-iOS/StaticViewComponent/StudyApplyMessageView.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyView.swift
Labels: review needed

#57 프로필 프로젝트 수정 키보드 이벤트 처리
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/BaseComponent/BaseProfileView.swift
  Terminal-iOS/Extensions-Utillities/UIViewController+Ext.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ApplyUserDetail/ApplyUserDetailView.swift
  Terminal-iOS/Set/Component/ProjectSNSModifyView 2.swift
  Terminal-iOS/Set/Component/ProjectTableView.swift
  Terminal-iOS/Set/Location/LocationModifyWireFrame 2.swift
  Terminal-iOS/Set/MyProfile/ProfileDetailView.swift
  Terminal-iOS/Set/Profile/ProfileModifyRemoteManager 2.swift
  Terminal-iOS/Set/Profile/ProfileModifyView.swift
  Terminal-iOS/Set/Project/ProjectCell.swift
  Terminal-iOS/Set/Project/ProjectModifyView 2.swift
  Terminal-iOS/Set/Project/ProjectModifyView.swift
  Terminal-iOS/Set/SNS/SNSModifyView 2.swift
  Terminal-iOS/Set/Set/SetView.swift
  Terminal-iOS/Utils/Contents 2.swift
  TestViewController 2.swift
Labels: review needed

#61 스터디 카테고리 뷰 수정
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/Assets.xcassets/newCategory/bigdata.imageset/Contents 2.json
  Terminal-iOS/Assets.xcassets/newCategory/bigdata.imageset/Contents.json
  Terminal-iOS/Assets.xcassets/newCategory/bigdata.imageset/Image 2.png
  Terminal-iOS/Assets.xcassets/newCategory/bigdata.imageset/Image.png
  Terminal-iOS/Assets.xcassets/newCategory/embedded.imageset/Contents 2.json
  Terminal-iOS/Assets.xcassets/newCategory/embedded.imageset/Contents.json
  Terminal-iOS/Assets.xcassets/newCategory/embedded.imageset/Image 2.png
  Terminal-iOS/Assets.xcassets/newCategory/embedded.imageset/Image.png
  Terminal-iOS/Assets.xcassets/newCategory/systemNetwork.imageset/Contents 2.json
  Terminal-iOS/Assets.xcassets/newCategory/systemNetwork.imageset/Contents.json
  Terminal-iOS/Assets.xcassets/newCategory/systemNetwork.imageset/Image 2.png
  Terminal-iOS/Assets.xcassets/newCategory/systemNetwork.imageset/Image.png
  Terminal-iOS/Assets.xcassets/newCategory/web.imageset/Contents 2.json
  Terminal-iOS/Assets.xcassets/newCategory/web.imageset/Contents.json
  Terminal-iOS/Assets.xcassets/newCategory/web.imageset/Image 2.png
  Terminal-iOS/Assets.xcassets/newCategory/web.imageset/Image.png
  Terminal-iOS/Entity/StudyDetail.swift
  Terminal-iOS/Entity/Terminal.swift
  Terminal-iOS/Login/IntroRemoteDataManager.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Study/SelectCategory/SelectCategoryView.swift
  Terminal-iOS/Study/StudyCategory/CategoryCell.swift
  Terminal-iOS/Study/StudyCategory/Component/CategoryImageView.swift
  Terminal-iOS/Study/StudyCategory/DataManager/StudyCategoryRemoteManager.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryInteractor.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryPresenter.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryProtocols.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryView.swift
  Terminal-iOS/Study/StudyCategory/StudyCategoryWireFrame.swift
  Terminal-iOS/Study/StudyList/StudyListProtocols.swift
  Terminal-iOS/Study/StudyList/StudyListView.swift
  Terminal-iOS/Study/StudyList/StudyListWireFrame.swift
Labels: review needed

#63 TerminalAlertMessage 수정
  Terminal-iOS/Entity/Study.swift
  Terminal-iOS/Entity/TerminalAlertMessage.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/DelegateHost/DelegateHostPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/DelegateHost/DelegateHostView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/MyApplyStudyDetail/MyApplyStudyDetailView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Set/Set/SetView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultRemoteDataManager.swift
  Terminal-iOS/Study/StudyList/DataManager/StudyListLocalDataManager.swift
  Terminal-iOS/Study/StudyList/StudyListInteractor.swift
Labels: HotFix

#67 CreateStudy - SelectLocation
  Terminal-iOS/BaseComponent/BaseEditableStudyDetailView.swift
  Terminal-iOS/BaseComponent/BaseProfileRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/AddNotice/AddNoticeRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyInteractor.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyPresenter.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyProtocols.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyRemoteManager.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyView.swift
  Terminal-iOS/Study/CreateStudy/CreateStudyWireFrame.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SelectLocation/Component/BottomView.swift
  Terminal-iOS/Study/CreateStudy/LocationView/SelectLocation/SelectLocationViewView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultPresenter.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultWireFrame.swift
Labels: review needed

#68 Feature/study list
  Terminal-iOS/Extensions-Utillities/UIViewController+Ext.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/MemberCollectionViewCell.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyPresenter.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyProtocols.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultProtocols.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyResultView/SearchStudyResultWireFrame.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyView.swift
  Terminal-iOS/Study/SearchStudy/SearchStudyWireFrame.swift
  Terminal-iOS/Study/StudyList/DataManager/StudyListRemoteDataManager.swift
  Terminal-iOS/Study/StudyList/StudyCell.swift
  Terminal-iOS/Study/StudyList/StudyListInteractor.swift
  Terminal-iOS/Study/StudyList/StudyListView.swift
Labels: review needed

#73 설정창 프로필 디테일 수정
  Terminal-iOS/Network/BaseInterceptor.swift
  Terminal-iOS/Network/TerminalRouter.swift
  Terminal-iOS/Set/Set/Component/ProfileCell.swift
  Terminal-iOS/Set/Set/SetView.swift
Labels: review completed

#80 AlertView + StudyDetail
  Terminal-iOS.xcodeproj/project.pbxproj
  Terminal-iOS/BaseComponent/BaseProfileView.swift
  Terminal-iOS/Entity/TerminalAlertMessage.swift
  Terminal-iOS/Extensions-Utillities/String+Ext.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/ModifyStudy/ModifyStudyRemoteDataManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/SNSIconImageView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/SNSIconsView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/StudyDetailSNSView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/Component/TitleWithContentView.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/DataManager/StudyDetailRemoteManager.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailInteractor.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailPresenter.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailProtocols.swift
  Terminal-iOS/MyStudy/StudyDetail/ViewComponent/StudyDetail/StudyDetailView.swift
Labels: review completed
